---
# tasks file for install-php

- name: install ppa
  apt_repository:
    repo: ppa:ondrej/php

- name: install php7.4
  apt:
    name: [ 'php7.4' ]
    state: present

- name: install php-modules
  apt:
    name: [ 'php7.4-dev', 'php7.4-fpm', 'php7.4-cli', 'php7.4-gd', 'php7.4-pgsql', 'php7.4-imap', 'php7.4-mbstring', 'php7.4-xml', 'php7.4-curl', 'php7.4-bcmath', 'php7.4-intl', 'php7.4-zip', 'php-imagick',  'php7.4-memcache' ]
    state: present

