---
# tasks file for create_user

- name: create user
  user:
    name: deploy
    shell: /bin/bash
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/{{ username }}
